### ISSUE TITLE
under windows path separator need specialized

### ISSUE THREAD

**Issue by openalmeida** [gmr/glyphicons-sprite-generator#3]
Great job, 
nice tool for twitter bootstrap icon sprite,
especially icon color change&customed

nearly line 74
ICON_NAME = re.compile(r'glyphicons\\png\\glyphicons_\d{3}_([\w_@\+\-]+)\.png')

nearly line 196
files = glob.glob("glyphicons\\png\\*.png") 

just use os.sep instead, i think. :p

**Comment by gmr** [comment]
A bit late, but... Commit 13f8edfd5 should do this.
